export const mobileLegendsData = [
    {
        name: '366 Diamonds',
        stock: 1000,
        discount : null,
        current_price : 100000,
        price_before_discount : null,
        delivery_time : '10 Menit Kirim',
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    },
    {
        name: '366 Diamonds',
        stock: 500,
        discount : 50,
        current_price : 100000,
        price_before_discount : 200000,
        delivery_time : null,
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    },
    {
        name: '2010 Diamonds',
        stock: 500,
        discount : 50,
        current_price : 100000,
        price_before_discount : 200000,
        delivery_time : '10 Menit Kirim',
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    },
    {
        name: '366 Diamonds',
        stock: 1000,
        discount : null,
        current_price : 100000,
        price_before_discount : null,
        delivery_time : '10 Menit Kirim',
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    },
    {
        name: '366 Diamonds',
        stock: 500,
        discount : 50,
        current_price : 100000,
        price_before_discount : 200000,
        delivery_time : null,
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    },
    {
        name: '2010 Diamonds',
        stock: 500,
        discount : 50,
        current_price : 100000,
        price_before_discount : 200000,
        delivery_time : '10 Menit Kirim',
        product_sold : 1000,
        product_desc : `Deskripsi produk mobile legends dari toko UlalaShop yang paling termurah. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s`,
    }
];