import Head from 'next/head'
import styled from 'styled-components'
import { contentData } from '../utils/allContent'
import { mobileLegendsData } from '../utils/mlContent'

import Header from '../components/Layout/Header'
import Footer from '../components/Layout/Footer'
import Title from '../components/Title'
import Card from '../components/Card'

const Main = styled.div`
    max-width: 600px;
    height: auto;
    margin-left: auto;
    margin-right: auto;
    background-color: white;
    padding-top: 1rem;
`;

const CardContainer = styled.div`
    width: 100%;
    user-select: none;
    padding: 1rem 1rem 2.5rem 1rem;
    overflow-y: hidden;
    overflow-x: auto;
`;

const CardWrapper = styled.div`
    width: 100%;
    height: 100%;
    flex-direction: row;
    display: flex;
`;

const ListCard = styled.div`
    width: 100%;
    flex: none;
    flex-direction: row;
    display: flex;
    cursor: pointer;
`;

export default function Home() {
    return (
        <>
            <Header/>
            <Main>
                <Head>
                    <title>Itemku</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/itemku-icon.png" />
                </Head>

                <Title name={`Termurah di Seluruh Indonesia`}/>

                <CardContainer>
                    <CardWrapper>
                        <ListCard>
                            {contentData.map(({ name, game_name, stock, discount, current_price, price_before_discount, delivery_time, product_sold  }) => (
                                <Card
                                    name={name}
                                    brandName={game_name}
                                    amount={stock}
                                    number={discount}
                                    priceBefore={price_before_discount}
                                    price={current_price}
                                    badgesDetail={delivery_time}
                                    soldAmount={product_sold}
                                />
                            ))}
                            
                        </ListCard>
                    </CardWrapper>
                </CardContainer>

                <Title name={`Produk Mobile Legends terpopuler`}/>

                <CardContainer>
                    <CardWrapper>
                        <ListCard>
                            {mobileLegendsData.map(({ name, stock, discount, current_price, price_before_discount, delivery_time, product_sold  }) => (
                                <Card
                                    name={name}
                                    // brandName={game_name}
                                    amount={stock}
                                    number={discount}
                                    priceBefore={price_before_discount}
                                    price={current_price}
                                    badgesDetail={delivery_time}
                                    soldAmount={product_sold}
                                />
                            ))}
                        </ListCard>
                    </CardWrapper>
                </CardContainer>

            </Main>
            <Footer/>
        </>
        
    )
}
