import Head from 'next/head'
import styled from 'styled-components'

import Header from '../components/Layout/Header'
import Footer from '../components/Layout/Footer'
import Title from '../components/Title'
import Card from '../components/Card'

const Main = styled.div`
    max-width: 600px;
    height: auto;
    margin-left: auto;
    margin-right: auto;
    background-color: white;
    padding-top: 1rem;
`;

const CardContainer = styled.div`
    width: 100%;
    user-select: none;
    padding: 1rem 1rem 2.5rem 1rem;
    overflow-y: hidden;
    overflow-x: auto;
`;

const CardWrapper = styled.div`
    width: 100%;
    height: 100%;
    flex-direction: row;
    display: flex;
`;

const ListCard = styled.div`
    width: 100%;
    flex: none;
    flex-direction: row;
    display: flex;
    cursor: pointer;
`;

export default function Home() {
    return (
        <>
            <Header/>
            <Main>
                <Head>
                    <title>Itemku</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/itemku-icon.png" />
                </Head>

                <Title name={`Termurah di Seluruh Indonesia`}/>

                <CardContainer>
                    <CardWrapper>
                        <ListCard>
                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />
                        </ListCard>
                    </CardWrapper>
                </CardContainer>

                <Title name={`Produk Mobile Legends terpopuler`}/>

                <CardContainer>
                    <CardWrapper>
                        <ListCard>
                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />

                            <Card
                                name={`600 UC`}
                                brandName={`PUBG Mobile`}
                                amount={1000}
                                number={50}
                                priceBefore={200000}
                                price={100000}
                                badgesDetail={`10 Menit Kirim`}
                                soldAmount={1000}
                            />
                        </ListCard>
                    </CardWrapper>
                </CardContainer>

            </Main>
            <Footer/>
        </>
        
    )
}
